version: 2.1
executors:
  main:
    docker:
      - image: 'circleci/node:12'

jobs:
  install_dependencies:
    executor: main
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - node-v1-{{ .Branch }}-
            - node-v1-
      - run: npm ci
      - run: npm run install-peers
      - save_cache:
          paths:
            - ./node_modules
          key: node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
  build:
    executor: main
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run:
          name: Building src
          command: npm run build
      - persist_to_workspace:
          root: build
          paths:
            - "*"
  deploy:
    executor: main
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - attach_workspace:
          at: build
      - run:
          name: Publish to NPM
          command: ./scripts/publish.sh
  release:
    executor: main
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "83:ef:64:3f:0e:e7:7a:49:11:de:b2:b6:63:5a:15:0d"
      - run:
          name: Setup git config
          command: |
                git config user.email "$GIT_EMAIL"
                git config user.name "$GIT_USERNAME"
      - run:
          name: Tag release
          command: ./scripts/tag_release.sh
  lint:
    executor: main
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run:
          name: Linting javascript
          command: npm run lint
  test:
    executor: main
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run:
          name: Running automated tests
          command: npm run test
  update_test_coverage:
    executor: main
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run:
          name: Update coveralls test coverage
          command: ./scripts/update_coverage.sh

workflows:
  version: 2
  main:
    jobs:
      - install_dependencies
      - lint:
          requires:
            - install_dependencies
      - test:
          requires:
            - install_dependencies
          filters:
            branches:
              ignore: master
      - update_test_coverage:
          requires:
            - install_dependencies
          filters:
            branches:
              only: master
      - build:
          requires:
            - install_dependencies
      - deploy:
          requires:
            - build
            - lint
            - update_test_coverage
          filters:
            branches:
              only: master
      - release:
          requires:
            - deploy
          filters:
            branches:
              only: master
  